import type { Service, PortfolioItem } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const getImageUrl = (id: string) => PlaceHolderImages.find(p => p.id === id)?.imageUrl || '';
const getImageHint = (id: string) => PlaceHolderImages.find(p => p.id === id)?.imageHint || '';

export const services: Service[] = [
  {
    id: 'branding',
    title: 'Branding & Identity',
    category: 'Design',
    icon: 'Palette',
    description: 'Crafting unique visual identities that tell your story.',
    longDescription: 'Our branding and identity service involves a deep dive into your company\'s values and mission. We develop a comprehensive brand guide that includes logo design, color palettes, typography, and voice. The result is a cohesive and memorable brand that resonates with your target audience and sets you apart from the competition.',
  },
  {
    id: 'web-dev',
    title: 'Web Development',
    category: 'Development',
    icon: 'Code',
    description: 'Building responsive, high-performance websites.',
    longDescription: 'We specialize in creating custom websites that are not only visually stunning but also fast, secure, and optimized for all devices. From corporate sites to e-commerce platforms, our development process is centered around user experience, scalability, and achieving your business objectives. We use the latest technologies to ensure your site is a powerful tool for growth.',
  },
  {
    id: 'app-dev',
    title: 'App Development',
    category: 'Development',
    icon: 'Smartphone',
    description: 'Creating intuitive mobile experiences for iOS and Android.',
    longDescription: 'We design and develop native and cross-platform mobile apps that engage users and deliver value. Our process covers the full lifecycle from ideation and UI/UX design to development, testing, and deployment on the App Store and Google Play. We focus on creating apps that are user-friendly, reliable, and performant.',
  },
  {
    id: 'marketing',
    title: 'Digital Marketing',
    category: 'Marketing',
    icon: 'Megaphone',
    description: 'Driving growth and engagement through strategic campaigns.',
    longDescription: 'Our digital marketing services are designed to increase your online visibility and drive qualified traffic. We offer a range of solutions including social media management, content marketing, email campaigns, and pay-per-click (PPC) advertising. We create data-driven strategies to connect with your audience and achieve measurable results.',
  },
  {
    id: 'seo',
    title: 'SEO & Analytics',
    category: 'Marketing',
    icon: 'TrendingUp',
    description: 'Optimizing for search engines to boost organic traffic.',
    longDescription: 'Improve your search engine rankings and gain valuable insights with our SEO and analytics services. We conduct thorough keyword research, on-page and off-page optimization, and technical SEO audits. Paired with advanced analytics, we track performance and refine strategies to ensure you\'re reaching the right audience and maximizing ROI.',
  },
  {
    id: 'video',
    title: 'Video Production',
    category: 'Design',
    icon: 'Film',
    description: 'Producing compelling video content that captivates.',
    longDescription: 'From promotional videos to animated explainers, we handle all aspects of video production. Our team works with you from scriptwriting and storyboarding to shooting, editing, and post-production. We create high-quality video content that tells your brand\'s story and engages your audience across all platforms.',
  },
  {
    id: 'ui-ux',
    title: 'UI/UX Design',
    category: 'Design',
    icon: 'Search',
    description: 'Designing user-centric interfaces for seamless experiences.',
    longDescription: 'A great product starts with a great user experience. Our UI/UX design process is rooted in research and user testing to create interfaces that are not only beautiful but also intuitive and easy to use. We focus on creating a seamless journey for your users, which should lead to higher engagement and satisfaction.',
  },
  {
    id: 'ai-integration',
    title: 'AI Integration',
    category: 'Development',
    icon: 'Bot',
    description: 'Leveraging AI to build smarter applications.',
    longDescription: 'Unlock new possibilities with Artificial Intelligence. We help businesses integrate AI and machine learning models into their products and services. From chatbots and recommendation engines to predictive analytics, we build intelligent solutions that automate processes, enhance user experience, and provide a competitive edge.',
  },
];

export const portfolioItems: PortfolioItem[] = [
  {
    id: 'p1',
    title: 'Project Nova',
    category: 'Web Development',
    description: 'A cutting-edge e-commerce platform for a fashion startup.',
    longDescription: 'Project Nova was a full-scale web development project for a new fashion brand. We built a custom Shopify theme with a focus on high-quality visuals and a seamless checkout experience. The site features advanced filtering, a lookbook gallery, and is fully optimized for mobile commerce, resulting in a 30% increase in conversion rates post-launch.',
    imageUrl: getImageUrl('portfolio-1'),
    imageHint: getImageHint('portfolio-1'),
  },
  {
    id: 'p2',
    title: 'Aura Branding',
    category: 'Branding & Identity',
    description: 'Complete brand identity overhaul for a wellness company.',
    longDescription: 'Aura, a wellness company, needed a brand refresh. We developed a new brand identity that included a new logo, color scheme, and packaging design. The new branding reflects their values of nature and tranquility, and has been instrumental in their successful expansion into new markets.',
    imageUrl: getImageUrl('portfolio-2'),
    imageHint: getImageHint('portfolio-2'),
  },
  {
    id: 'p3',
    title: 'ConnectApp',
    category: 'App Development',
    description: 'A social networking app for professionals.',
    longDescription: 'ConnectApp is a mobile application designed to help professionals network. We handled the entire project from UI/UX design to native iOS and Android development. The app includes features like profile creation, direct messaging, and event discovery. It gained 50,000 users in its first three months.',
    imageUrl: getImageUrl('portfolio-3'),
    imageHint: getImageHint('portfolio-3'),
  },
  {
    id: 'p4',
    title: 'Go-To Market Strategy',
    category: 'Digital Marketing',
    description: 'Launched a new SaaS product with a multi-channel campaign.',
    longDescription: 'We partnered with a SaaS startup to launch their new product. Our team executed a comprehensive digital marketing strategy that included content marketing, social media advertising, and influencer outreach. The campaign generated over 1,000 trial sign-ups in the first month and established a strong initial user base.',
    imageUrl: getImageUrl('portfolio-4'),
    imageHint: getImageHint('portfolio-4'),
  },
  {
    id: 'p5',
    title: 'Organic Growth',
    category: 'SEO & Analytics',
    description: 'Doubled organic traffic for a B2B tech company.',
    longDescription: 'Our SEO strategy for a B2B tech client involved a deep technical audit, content gap analysis, and a sustained link-building campaign. Over six months, we doubled their organic search traffic and achieved first-page rankings for their primary target keywords, significantly increasing their lead generation.',
    imageUrl: getImageUrl('portfolio-5'),
    imageHint: getImageHint('portfolio-5'),
  },
  {
    id: 'p6',
    title: 'Brand Story Film',
    category: 'Video Production',
    description: 'A short film telling the story of a heritage brand.',
    longDescription: 'We produced a cinematic brand story film for a company with a rich history. The film was used on their website, in social media campaigns, and at trade shows. The emotionally resonant storytelling helped to strengthen customer loyalty and communicate the brand\'s legacy to a new generation.',
    imageUrl: getImageUrl('portfolio-6'),
    imageHint: getImageHint('portfolio-6'),
  },
   {
    id: 'p7',
    title: 'Fintech UI/UX',
    category: 'UI/UX Design',
    description: 'Redesigned a mobile banking app for better usability.',
    longDescription: 'We conducted extensive user research to redesign a mobile banking app, focusing on simplifying complex financial tasks. The new design introduced a cleaner interface, personalized dashboards, and intuitive navigation. User satisfaction scores increased by 40% after the relaunch.',
    imageUrl: getImageUrl('portfolio-7'),
    imageHint: getImageHint('portfolio-7'),
  },
  {
    id: 'p8',
    title: 'Social Buzz',
    category: 'Digital Marketing',
    description: 'Viral social media campaign for a consumer product.',
    longDescription: 'For a new consumer gadget, we created a viral marketing campaign centered around user-generated content and a TikTok challenge. The campaign reached over 10 million users and drove a massive spike in sales, selling out the initial production run in just two weeks.',
    imageUrl: getImageUrl('portfolio-8'),
    imageHint: getImageHint('portfolio-8'),
  },
];
